### ISSUE TITLE
data["Processor"] = cinfo['brand'] KeyError: 'brand'

### ISSUE THREAD

**Issue by Lqzhi** [Pure-Peace/system-info#1]
Code：
# -*- conding:utf-8 -*-
from system_info.sysinfo import os_info

if __name__ == '__main__':
    print(os_info.platformName())

Error:

Traceback (most recent call last):
  File "E:\Code\Python\SysMonitor\main.py", line 2, in <module>
    from system_info.sysinfo import os_info
  File "E:\Code\Python\TkCalculator\SysMonitor\lib\site-packages\system_info\sysinfo.py", line 230, in <module>
    sysInfo = os_info.systemSpec()
  File "E:\Code\Python\TkCalculator\SysMonitor\lib\site-packages\system_info\sysinfo.py", line 55, in systemSpec
    data["Processor"] = cinfo['brand']
KeyError: 'brand'

**Comment by Lqzhi** [comment]
![image](https://github.com/Pure-Peace/system-info/assets/47026918/656a3423-61b1-4850-996d-555e659cb7e3)
